"""empty message

Revision ID: 396618b69bf2
Revises: 32e8153cef61
Create Date: 2018-09-21 14:07:44.541659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396618b69bf2'
down_revision = '32e8153cef61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_tw_token', sa.LargeBinary(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_tw_token')
    # ### end Alembic commands ###
