"""empty message

Revision ID: 4bf8cabc55b9
Revises: b49992f4fdfd
Create Date: 2018-06-29 22:42:11.546340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf8cabc55b9'
down_revision = 'b49992f4fdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transferwise_token', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transferwise_token')
    # ### end Alembic commands ###
