"""empty message

Revision ID: 4efe41d98c04
Revises: da42ce07df85
Create Date: 2018-07-19 22:07:29.239078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efe41d98c04'
down_revision = 'da42ce07df85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transerwise_profile_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transerwise_profile_id')
    # ### end Alembic commands ###
