"""empty message

Revision ID: 556d018eeecf
Revises: a776a0e4f012
Create Date: 2018-07-25 17:03:44.674088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556d018eeecf'
down_revision = 'a776a0e4f012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_currency', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'home_currency')
    # ### end Alembic commands ###
