"""empty message

Revision ID: 6880d8adb367
Revises: 8814a5548808
Create Date: 2018-10-07 13:24:50.486512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6880d8adb367'
down_revision = '8814a5548808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_slack_token', sa.String(length=240), nullable=True),
    sa.Column('team_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('organsation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organisations', ['organsation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organsation_id')
    op.drop_table('organisations')
    # ### end Alembic commands ###
