"""empty message

Revision ID: 6b4a208a28b6
Revises: 4bf8cabc55b9
Create Date: 2018-07-01 13:24:34.890132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4a208a28b6'
down_revision = '4bf8cabc55b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'slack_id')
    # ### end Alembic commands ###
