"""empty message

Revision ID: 8814a5548808
Revises: 396618b69bf2
Create Date: 2018-09-21 16:12:10.828133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8814a5548808'
down_revision = '396618b69bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transferwise_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transferwise_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
