"""empty message

Revision ID: a4a301d2c293
Revises: c2d2f3877dc4
Create Date: 2018-09-21 14:01:21.963472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a301d2c293'
down_revision = 'c2d2f3877dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_tw_token', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_tw_token')
    # ### end Alembic commands ###
