"""empty message

Revision ID: a776a0e4f012
Revises: 4efe41d98c04
Create Date: 2018-07-19 22:28:03.186613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a776a0e4f012'
down_revision = '4efe41d98c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transferwise_profile_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'transerwise_profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transerwise_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'transferwise_profile_id')
    # ### end Alembic commands ###
