"""empty message

Revision ID: e49ead68c044
Revises: 814c2272c24b
Create Date: 2018-09-11 18:23:43.077684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49ead68c044'
down_revision = '814c2272c24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_tw_token', sa.String(length=240), nullable=True))
    op.drop_column('users', 'encryped_tw_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryped_tw_token', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.drop_column('users', 'encrypted_tw_token')
    # ### end Alembic commands ###
