"""empty message

Revision ID: fef8e788fd39
Revises: 6880d8adb367
Create Date: 2018-10-07 14:37:46.429470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef8e788fd39'
down_revision = '6880d8adb367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_organsation_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    op.drop_column('users', 'organsation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organsation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organsation_id_fkey', 'users', 'organisations', ['organsation_id'], ['id'])
    op.drop_column('users', 'organisation_id')
    # ### end Alembic commands ###
